// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Main.h"
#include "screens/ui_Pedal.h"
#include "screens/ui_Tuner.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_lineasset_png);    // assets/LineAsset.png
LV_IMG_DECLARE(ui_img_tunerasset_png);    // assets/TunerAsset.png
LV_IMG_DECLARE(ui_img_flatindicator_png);    // assets/FlatIndicator.png

// FONTS
LV_FONT_DECLARE(ui_font_IndexFont);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
