// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_events.h"
#include "AudioPath.h"

extern DisplayManager_t g_display_mgr;
extern AudioChannel_t Channel1;
extern AudioChannel_t Channel2;

lv_group_t* encoder_group = NULL;
lv_group_t* ui_get_encoder_group(void) { return encoder_group; }
void ui_set_encoder_group(lv_group_t* g) { encoder_group = g; }

void createGroupMain(lv_event_t * e)
{
	// Your code here
    lv_group_t* g = ui_get_encoder_group();
    if (!g) { return; }

    lv_group_remove_all_objs(g);
    encoder_group = g;
    // Preset dropdown
    lv_group_add_obj(g, ui_PresetSelect);

    // Channel 1 effect nodes
    lv_group_add_obj(g, ui_Select_Box1);
    lv_group_add_obj(g, ui_Select_Box2);
    lv_group_add_obj(g, ui_Select_Box3);
    lv_group_add_obj(g, ui_Select_Box4);
    lv_group_add_obj(g, ui_Select_Box5);
    lv_group_add_obj(g, ui_EqSelect);

    // Channel 2 effect nodes
    lv_group_add_obj(g, ui_Select_Box6);
    lv_group_add_obj(g, ui_Select_Box7);
    lv_group_add_obj(g, ui_Select_Box8);
    lv_group_add_obj(g, ui_Select_Box9);
    lv_group_add_obj(g, ui_Select_Box10);
    lv_group_add_obj(g, ui_EqSelect1);
}

void ui_event_preset_changed(lv_event_t * e)
{
	// Your code here
	int preset_idx = lv_dropdown_get_selected(ui_PresetSelect);
	g_display_mgr.PresetIdx = preset_idx;

	lv_obj_t* boxes[10] = {
		ui_Select_Box1, ui_Select_Box2, ui_Select_Box3, ui_Select_Box4, ui_Select_Box5,
		ui_Select_Box6, ui_Select_Box7, ui_Select_Box8, ui_Select_Box9, ui_Select_Box10
	};

	for (int i = 0; i < 10; i++) {
		int isChannel2 = (i >= 5);
		int internal_slot = isChannel2 ? (i - 5) : i;

		AudioChannel_t* live_channel = isChannel2 ? &Channel2 : &Channel1;

		Effect_t* preset_effect = isChannel2
			? &presets[preset_idx].Channel2.chain[internal_slot]
			: &presets[preset_idx].Channel1.chain[internal_slot];

		int effect_type = 0;

		if (preset_effect->process != NULL && preset_effect->process != bypassProcess) {
		    for (int j = 0; j < NUM_EFFECTS; j++) {
		        if (preset_effect->process == effectList[j].process) {
		            effect_type = j;
		            break;
		        }
		    }
		}

		g_display_mgr.effectsIdx[i] = effect_type;
		if (effect_type > 0 && effect_type < NUM_EFFECTS) {

		    if (live_channel->chain[internal_slot].process != preset_effect->process) {
		        live_channel->chain[internal_slot].process = preset_effect->process;
		        live_channel->chain[internal_slot].enabled = true;
		        lv_memset(live_channel->chain[internal_slot].state, 0, sizeof(live_channel->chain[internal_slot].state));
		    }

		    lv_memcpy(live_channel->chain[internal_slot].params, preset_effect->params, sizeof(live_channel->chain[internal_slot].params));
		}
		else {
		    live_channel->chain[internal_slot].process = preset_effect->process; // Keeps bypassProcess safely
		    live_channel->chain[internal_slot].enabled = false;
		    lv_memcpy(live_channel->chain[internal_slot].params, preset_effect->params, sizeof(live_channel->chain[internal_slot].params));
		}

		if (boxes[i] != NULL) {
			lv_obj_t* box_label = lv_obj_get_child(boxes[i], 0);
			if (box_label != NULL) {
				lv_label_set_text(box_label, effect_db[effect_type].abbreviation);
			}
		}
	}

	Channel1.chainLen = MAX_EFFECT_COUNT;
	Channel2.chainLen = MAX_EFFECT_COUNT;
	g_display_mgr.presetChanged = 1;
}

void uiUpdatePedalScreen(lv_event_t * e)
{
	// Your code here
	char idxBuf[8];
	lv_snprintf(idxBuf, sizeof(idxBuf), "%02d:", g_display_mgr.activeSlotIdx + 1);
	lv_label_set_text(ui_BGEffect, idxBuf);

	AudioChannel_t* active_channel = (g_display_mgr.activeSlotIdx < 5) ? &Channel1 : &Channel2;
	int internal_slot_idx = (g_display_mgr.activeSlotIdx < 5) ? g_display_mgr.activeSlotIdx : g_display_mgr.activeSlotIdx - 5;

	Effect_t* active_effect = &active_channel->chain[internal_slot_idx];

	int effect_type = 0;
	if (active_effect->process != NULL && active_effect->process != bypassProcess) {
		for (int j = 0; j < NUM_EFFECTS; j++) {
			if (active_effect->process == effectList[j].process) {
				effect_type = j;
				break;
			}
		}
	}

	EffectMetadata_t* md = &effect_db[effect_type];

	lv_dropdown_set_selected(ui_PedalSel1, effect_type);
	lv_label_set_text(ui_PedalDescripton, md->description);

	lv_obj_t* arcs[6] = { ui_Parameter, ui_Parameter1, ui_Parameter2, ui_Parameter3, ui_Parameter4, ui_Parameter5 };
	lv_obj_t* txt_labels[6] = { ui_ParamTxt, ui_ParamTxt1, ui_ParamTxt2, ui_ParamTxt3, ui_ParamTxt4, ui_ParamTxt5 };
	lv_obj_t* val_labels[6] = { ui_ParamValue, ui_ParamValue1, ui_ParamValue2, ui_ParamValue3, ui_ParamValue4, ui_ParamValue5 };

	for (int i = 0; i < 6; i++) {
		if (lv_strcmp(md->paramNames[i], "--") == 0) {
			lv_obj_add_flag(txt_labels[i], LV_OBJ_FLAG_HIDDEN);
			lv_obj_add_flag(val_labels[i], LV_OBJ_FLAG_HIDDEN);
			lv_obj_add_flag(arcs[i], LV_OBJ_FLAG_HIDDEN);
		}
		else {
			lv_obj_clear_flag(txt_labels[i], LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(val_labels[i], LV_OBJ_FLAG_HIDDEN);
			lv_label_set_text(txt_labels[i], md->paramNames[i]);

			float current_param_value = active_effect->params[i];

			char valBuf[16];
			lv_snprintf(valBuf, sizeof(valBuf), "%d", (int)current_param_value);
			lv_label_set_text(val_labels[i], valBuf);

			lv_obj_clear_flag(arcs[i], LV_OBJ_FLAG_HIDDEN);
			lv_arc_set_range(arcs[i], md->paramMin[i], md->paramMax[i]);
			lv_arc_set_value(arcs[i], current_param_value);
		}
	}
}

void UpdateCab(lv_event_t * e)
{
	// Your code here
}

void ui_group_set_screen_pedal1(lv_event_t * e)
{
	// Your code here
}

void createGroupPedal(lv_event_t * e)
{
	// Your code here
    lv_group_t* g = ui_get_encoder_group();
    if (!g) return;

    lv_group_remove_all_objs(g);
    lv_group_add_obj(g, ui_BackButton1);
    lv_group_add_obj(g, ui_PedalSel1);

}

void ui_UpdatePedalFromDropdown(lv_event_t * e)
{
	// Your code here
	int chosenEffectId = lv_dropdown_get_selected(ui_PedalSel1);
	g_display_mgr.effectsIdx[g_display_mgr.activeSlotIdx] = chosenEffectId;

	AudioChannel_t* active_channel = (g_display_mgr.activeSlotIdx < 5) ? &Channel1 : &Channel2;
	int internal_slot_idx = (g_display_mgr.activeSlotIdx < 5) ? g_display_mgr.activeSlotIdx : g_display_mgr.activeSlotIdx - 5;

	if (chosenEffectId > 0 && chosenEffectId < NUM_EFFECTS) {
		active_channel->chain[internal_slot_idx] = effectList[chosenEffectId];
		active_channel->chain[internal_slot_idx].enabled = true;
		lv_memset(active_channel->chain[internal_slot_idx].state, 0, sizeof(active_channel->chain[internal_slot_idx].state));

		Effect_t* preset_src = (g_display_mgr.activeSlotIdx < 5)
			? &presets[g_display_mgr.PresetIdx].Channel1.chain[internal_slot_idx]
			: &presets[g_display_mgr.PresetIdx].Channel2.chain[internal_slot_idx];

		if (preset_src->process == effectList[chosenEffectId].process) {
			lv_memcpy(active_channel->chain[internal_slot_idx].params, preset_src->params, sizeof(active_channel->chain[internal_slot_idx].params));
		}
	} else {
		active_channel->chain[internal_slot_idx].process = bypassProcess;
		active_channel->chain[internal_slot_idx].enabled = false;
		lv_memset(active_channel->chain[internal_slot_idx].params, 0, sizeof(active_channel->chain[internal_slot_idx].params));
	}

	uiUpdatePedalScreen(e);
}

void ui_event_save_pedal(lv_event_t * e)
{
	// Your code here
    lv_obj_t* active_box = NULL;
    switch (g_display_mgr.activeSlotIdx) {
    case 0: active_box = ui_Select_Box1;  break;
    case 1: active_box = ui_Select_Box2;  break;
    case 2: active_box = ui_Select_Box3;  break;
    case 3: active_box = ui_Select_Box4;  break;
    case 4: active_box = ui_Select_Box5;  break;
    case 5: active_box = ui_Select_Box6;  break;
    case 6: active_box = ui_Select_Box7;  break;
    case 7: active_box = ui_Select_Box8;  break;
    case 8: active_box = ui_Select_Box9;  break;
    case 9: active_box = ui_Select_Box10; break;
    default: return;
    }

    if (active_box == NULL) return;

    lv_obj_t* box_label = lv_obj_get_child(active_box, 0);

    if (box_label != NULL) {
        lv_label_set_text(box_label, effect_db[g_display_mgr.effectsIdx[g_display_mgr.activeSlotIdx]].abbreviation);
    }

}

void ui_group_set_screen_main(lv_event_t * e)
{
	// Your code here
}

void UpdatePedalScreen(lv_event_t * e)
{
	// Your code here
}

void saveElementIdx(lv_event_t * e)
{
	// Your code here
    lv_obj_t* target = lv_event_get_target(e);

    if (target == ui_Select_Box1) {
        g_display_mgr.activeSlotIdx = 0;
    }
    else if (target == ui_Select_Box2) {
        g_display_mgr.activeSlotIdx = 1;
    }
    else if (target == ui_Select_Box3) {
        g_display_mgr.activeSlotIdx = 2;
    }
    else if (target == ui_Select_Box4) {
        g_display_mgr.activeSlotIdx = 3;
    }
    else if (target == ui_Select_Box5) {
        g_display_mgr.activeSlotIdx = 4;
    }
    else if (target == ui_Select_Box6) {
        g_display_mgr.activeSlotIdx = 5;
    }
    else if (target == ui_Select_Box7) {
        g_display_mgr.activeSlotIdx = 6;
    }
    else if (target == ui_Select_Box8) {
        g_display_mgr.activeSlotIdx = 7;
    }
    else if (target == ui_Select_Box9) {
        g_display_mgr.activeSlotIdx = 8;
    }
    else if (target == ui_Select_Box10) {
        g_display_mgr.activeSlotIdx = 9;
    }

    uiUpdatePedalScreen(e);
}

void createGroupTuner(lv_event_t * e)
{
	// Your code here
}

void PresetDropdownInit(lv_event_t * e)
{
	// Your code here
	char preset_names[MAX_PRESET_SIZE * 17];
	preset_names[0] = '\0';

	for (int i = 0; i < MAX_PRESET_SIZE; i++) {
	    lv_strcat(preset_names, presets[i].name);
	    if (i < MAX_PRESET_SIZE - 1) lv_strcat(preset_names, "\n");
	}

	const char* my_items = preset_names;
	lv_dropdown_set_options(ui_PresetSelect, my_items);

}

void PedalDropdownInit(lv_event_t * e)
{
	// Your code here
	char pedal_names[NUM_EFFECTS * 17];
	pedal_names[0] = '\0';

	for (int i = 0; i < NUM_EFFECTS; i++) {
	    lv_strcat(pedal_names, effect_db[i].name);
	    if (i < NUM_EFFECTS - 1) lv_strcat(pedal_names, "\n");
	}

	const char* my_items = pedal_names;
	lv_dropdown_set_options(ui_PedalSel1, my_items);
}
