// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PresetDropdownInit(lv_event_t * e);
void PedalDropdownInit(lv_event_t * e);
void createGroupMain(lv_event_t * e);
void ui_event_preset_changed(lv_event_t * e);
void saveElementIdx(lv_event_t * e);
void createGroupPedal(lv_event_t * e);
void ui_UpdatePedalFromDropdown(lv_event_t * e);
void uiUpdatePedalScreen(lv_event_t * e);
void ui_event_save_pedal(lv_event_t * e);
void createGroupTuner(lv_event_t * e);
void ui_group_set_screen_main(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
