// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Inst1Col[1] = {0x2F184B};
const ui_theme_variable_t _ui_theme_alpha_Inst1Col[1] = {255};

const ui_theme_variable_t _ui_theme_color_Inst2Col[1] = {0x800F2F};
const ui_theme_variable_t _ui_theme_alpha_Inst2Col[1] = {255};

const ui_theme_variable_t _ui_theme_color_neutral[1] = {0xEAE2D5};
const ui_theme_variable_t _ui_theme_alpha_neutral[1] = {255};

const ui_theme_variable_t _ui_theme_color_background[1] = {0x1A1A1A};
const ui_theme_variable_t _ui_theme_alpha_background[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

