// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_INST1COL 0
#define UI_THEME_COLOR_INST2COL 1
#define UI_THEME_COLOR_NEUTRAL 2
#define UI_THEME_COLOR_BACKGROUND 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Inst1Col[1];
extern const ui_theme_variable_t _ui_theme_alpha_Inst1Col[1];

extern const ui_theme_variable_t _ui_theme_color_Inst2Col[1];
extern const ui_theme_variable_t _ui_theme_alpha_Inst2Col[1];

extern const ui_theme_variable_t _ui_theme_color_neutral[1];
extern const ui_theme_variable_t _ui_theme_alpha_neutral[1];

extern const ui_theme_variable_t _ui_theme_color_background[1];
extern const ui_theme_variable_t _ui_theme_alpha_background[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
