// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_VolumeIndicator;
lv_obj_t * uic_PresetSelect;
lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_PresetSelect = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_VolumeIndicator = NULL;
lv_obj_t * ui_InstSelect1 = NULL;
lv_obj_t * ui_EffectNode2 = NULL;
lv_obj_t * ui_Select_Box1 = NULL;
lv_obj_t * ui_PedalIndicater1 = NULL;
lv_obj_t * ui_EffectNode3 = NULL;
lv_obj_t * ui_Select_Box2 = NULL;
lv_obj_t * ui_PedalIndicater3 = NULL;
lv_obj_t * ui_EffectNode1 = NULL;
lv_obj_t * ui_Select_Box3 = NULL;
lv_obj_t * ui_PedalIndicater2 = NULL;
lv_obj_t * ui_EffectNode4 = NULL;
lv_obj_t * ui_Select_Box4 = NULL;
lv_obj_t * ui_PedalIndicater4 = NULL;
lv_obj_t * ui_EffectNode5 = NULL;
lv_obj_t * ui_Select_Box5 = NULL;
lv_obj_t * ui_PedalIndicater5 = NULL;
lv_obj_t * ui_EqSelect = NULL;
lv_obj_t * ui_PedalIndicater8 = NULL;
lv_obj_t * ui_InstSelect2 = NULL;
lv_obj_t * ui_EffectNode6 = NULL;
lv_obj_t * ui_Select_Box6 = NULL;
lv_obj_t * ui_PedalIndicater6 = NULL;
lv_obj_t * ui_EffectNode7 = NULL;
lv_obj_t * ui_Select_Box7 = NULL;
lv_obj_t * ui_PedalIndicater7 = NULL;
lv_obj_t * ui_EffectNode8 = NULL;
lv_obj_t * ui_Select_Box8 = NULL;
lv_obj_t * ui_PedalIndicater9 = NULL;
lv_obj_t * ui_EffectNode9 = NULL;
lv_obj_t * ui_Select_Box9 = NULL;
lv_obj_t * ui_PedalIndicater10 = NULL;
lv_obj_t * ui_EffectNode10 = NULL;
lv_obj_t * ui_Select_Box10 = NULL;
lv_obj_t * ui_PedalIndicater11 = NULL;
lv_obj_t * ui_EqSelect1 = NULL;
lv_obj_t * ui_PedalIndicater12 = NULL;
// event funtions
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        createGroupMain(e);
    }
}

void ui_event_PresetSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_preset_changed(e);
    }
}

void ui_event_Select_Box1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_EqSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Pedal_screen_init);
    }
}

void ui_event_Select_Box6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        saveElementIdx(e);
    }
}

void ui_event_Select_Box10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Pedal_screen_init);
        saveElementIdx(e);
    }
}

void ui_event_EqSelect1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pedal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Pedal_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSelect = lv_dropdown_create(ui_Main);
    lv_dropdown_set_options(ui_PresetSelect, "01: Clean\n02: Metal\n03: Bass");
    lv_obj_set_width(ui_PresetSelect, 150);
    lv_obj_set_height(ui_PresetSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSelect, 0);
    lv_obj_set_y(ui_PresetSelect, 5);
    lv_obj_set_align(ui_PresetSelect, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PresetSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_PresetSelect, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSelect, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetSelect, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PresetSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PresetSelect, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_PresetSelect, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image1 = lv_image_create(ui_Main);
    lv_image_set_src(ui_Image1, &ui_img_lineasset_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image1, -100);
    lv_obj_set_y(ui_Image1, -50);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Main);
    lv_image_set_src(ui_Image2, &ui_img_lineasset_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image2, 190);
    lv_obj_set_y(ui_Image2, -50);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Main);
    lv_image_set_src(ui_Image3, &ui_img_lineasset_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image3, -100);
    lv_obj_set_y(ui_Image3, 76);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Main);
    lv_image_set_src(ui_Image4, &ui_img_lineasset_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image4, 190);
    lv_obj_set_y(ui_Image4, 76);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VolumeIndicator = lv_arc_create(ui_Main);
    lv_obj_set_width(ui_VolumeIndicator, 25);
    lv_obj_set_height(ui_VolumeIndicator, 25);
    lv_obj_set_x(ui_VolumeIndicator, 199);
    lv_obj_set_y(ui_VolumeIndicator, 10);
    lv_obj_set_align(ui_VolumeIndicator, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_VolumeIndicator, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_VolumeIndicator, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_VolumeIndicator, 75);
    lv_obj_set_style_radius(ui_VolumeIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_VolumeIndicator, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VolumeIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_VolumeIndicator, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_VolumeIndicator, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VolumeIndicator, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_VolumeIndicator, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_VolumeIndicator, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_VolumeIndicator, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeIndicator, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeIndicator, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_VolumeIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_InstSelect1 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_InstSelect1);
    lv_obj_set_width(ui_InstSelect1, 480);
    lv_obj_set_height(ui_InstSelect1, 97);
    lv_obj_set_x(ui_InstSelect1, 0);
    lv_obj_set_y(ui_InstSelect1, -50);
    lv_obj_set_align(ui_InstSelect1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InstSelect1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_InstSelect1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_InstSelect1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EffectNode2 = lv_obj_create(ui_InstSelect1);
    lv_obj_remove_style_all(ui_EffectNode2);
    lv_obj_set_width(ui_EffectNode2, 60);
    lv_obj_set_height(ui_EffectNode2, 50);
    lv_obj_set_x(ui_EffectNode2, -53);
    lv_obj_set_y(ui_EffectNode2, 62);
    lv_obj_set_align(ui_EffectNode2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box1 = lv_obj_create(ui_EffectNode2);
    lv_obj_set_width(ui_Select_Box1, 50);
    lv_obj_set_height(ui_Select_Box1, 50);
    lv_obj_set_x(ui_Select_Box1, -110);
    lv_obj_set_y(ui_Select_Box1, 42);
    lv_obj_set_align(ui_Select_Box1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box1, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst1Col);
    ui_object_set_themeable_style_property(ui_Select_Box1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst1Col);

    ui_PedalIndicater1 = lv_label_create(ui_Select_Box1);
    lv_obj_set_width(ui_PedalIndicater1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater1, -86);
    lv_obj_set_y(ui_PedalIndicater1, 0);
    lv_obj_set_align(ui_PedalIndicater1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater1, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode3 = lv_obj_create(ui_InstSelect1);
    lv_obj_remove_style_all(ui_EffectNode3);
    lv_obj_set_width(ui_EffectNode3, 60);
    lv_obj_set_height(ui_EffectNode3, 50);
    lv_obj_set_x(ui_EffectNode3, -53);
    lv_obj_set_y(ui_EffectNode3, 62);
    lv_obj_set_align(ui_EffectNode3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box2 = lv_obj_create(ui_EffectNode3);
    lv_obj_set_width(ui_Select_Box2, 50);
    lv_obj_set_height(ui_Select_Box2, 50);
    lv_obj_set_x(ui_Select_Box2, -110);
    lv_obj_set_y(ui_Select_Box2, 42);
    lv_obj_set_align(ui_Select_Box2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box2, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst1Col);
    ui_object_set_themeable_style_property(ui_Select_Box2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst1Col);

    ui_PedalIndicater3 = lv_label_create(ui_Select_Box2);
    lv_obj_set_width(ui_PedalIndicater3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater3, -86);
    lv_obj_set_y(ui_PedalIndicater3, 0);
    lv_obj_set_align(ui_PedalIndicater3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater3, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode1 = lv_obj_create(ui_InstSelect1);
    lv_obj_remove_style_all(ui_EffectNode1);
    lv_obj_set_width(ui_EffectNode1, 60);
    lv_obj_set_height(ui_EffectNode1, 50);
    lv_obj_set_x(ui_EffectNode1, -53);
    lv_obj_set_y(ui_EffectNode1, 62);
    lv_obj_set_align(ui_EffectNode1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box3 = lv_obj_create(ui_EffectNode1);
    lv_obj_set_width(ui_Select_Box3, 50);
    lv_obj_set_height(ui_Select_Box3, 50);
    lv_obj_set_x(ui_Select_Box3, -110);
    lv_obj_set_y(ui_Select_Box3, 42);
    lv_obj_set_align(ui_Select_Box3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box3, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst1Col);
    ui_object_set_themeable_style_property(ui_Select_Box3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst1Col);

    ui_PedalIndicater2 = lv_label_create(ui_Select_Box3);
    lv_obj_set_width(ui_PedalIndicater2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater2, -86);
    lv_obj_set_y(ui_PedalIndicater2, 0);
    lv_obj_set_align(ui_PedalIndicater2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater2, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode4 = lv_obj_create(ui_InstSelect1);
    lv_obj_remove_style_all(ui_EffectNode4);
    lv_obj_set_width(ui_EffectNode4, 60);
    lv_obj_set_height(ui_EffectNode4, 50);
    lv_obj_set_x(ui_EffectNode4, -53);
    lv_obj_set_y(ui_EffectNode4, 62);
    lv_obj_set_align(ui_EffectNode4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box4 = lv_obj_create(ui_EffectNode4);
    lv_obj_set_width(ui_Select_Box4, 50);
    lv_obj_set_height(ui_Select_Box4, 50);
    lv_obj_set_x(ui_Select_Box4, -110);
    lv_obj_set_y(ui_Select_Box4, 42);
    lv_obj_set_align(ui_Select_Box4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box4, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box4, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst1Col);
    ui_object_set_themeable_style_property(ui_Select_Box4, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst1Col);

    ui_PedalIndicater4 = lv_label_create(ui_Select_Box4);
    lv_obj_set_width(ui_PedalIndicater4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater4, -86);
    lv_obj_set_y(ui_PedalIndicater4, 0);
    lv_obj_set_align(ui_PedalIndicater4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater4, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode5 = lv_obj_create(ui_InstSelect1);
    lv_obj_remove_style_all(ui_EffectNode5);
    lv_obj_set_width(ui_EffectNode5, 60);
    lv_obj_set_height(ui_EffectNode5, 50);
    lv_obj_set_x(ui_EffectNode5, -53);
    lv_obj_set_y(ui_EffectNode5, 62);
    lv_obj_set_align(ui_EffectNode5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box5 = lv_obj_create(ui_EffectNode5);
    lv_obj_set_width(ui_Select_Box5, 50);
    lv_obj_set_height(ui_Select_Box5, 50);
    lv_obj_set_x(ui_Select_Box5, -110);
    lv_obj_set_y(ui_Select_Box5, 42);
    lv_obj_set_align(ui_Select_Box5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box5, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box5, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst1Col);
    ui_object_set_themeable_style_property(ui_Select_Box5, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst1Col);

    ui_PedalIndicater5 = lv_label_create(ui_Select_Box5);
    lv_obj_set_width(ui_PedalIndicater5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater5, -86);
    lv_obj_set_y(ui_PedalIndicater5, 0);
    lv_obj_set_align(ui_PedalIndicater5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater5, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EqSelect = lv_obj_create(ui_InstSelect1);
    lv_obj_set_width(ui_EqSelect, 50);
    lv_obj_set_height(ui_EqSelect, 50);
    lv_obj_set_x(ui_EqSelect, 150);
    lv_obj_set_y(ui_EqSelect, 0);
    lv_obj_set_align(ui_EqSelect, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EqSelect, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EqSelect, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_EqSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_EqSelect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_EqSelect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_EqSelect, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EqSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EqSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EqSelect, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_EqSelect, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst1Col);
    ui_object_set_themeable_style_property(ui_EqSelect, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst1Col);

    ui_PedalIndicater8 = lv_label_create(ui_EqSelect);
    lv_obj_set_width(ui_PedalIndicater8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater8, -86);
    lv_obj_set_y(ui_PedalIndicater8, 0);
    lv_obj_set_align(ui_PedalIndicater8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater8, "EQ");
    lv_obj_set_style_text_color(ui_PedalIndicater8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InstSelect2 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_InstSelect2);
    lv_obj_set_width(ui_InstSelect2, 480);
    lv_obj_set_height(ui_InstSelect2, 97);
    lv_obj_set_x(ui_InstSelect2, 0);
    lv_obj_set_y(ui_InstSelect2, 75);
    lv_obj_set_align(ui_InstSelect2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InstSelect2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_InstSelect2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_InstSelect2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EffectNode6 = lv_obj_create(ui_InstSelect2);
    lv_obj_remove_style_all(ui_EffectNode6);
    lv_obj_set_width(ui_EffectNode6, 60);
    lv_obj_set_height(ui_EffectNode6, 50);
    lv_obj_set_x(ui_EffectNode6, -53);
    lv_obj_set_y(ui_EffectNode6, 62);
    lv_obj_set_align(ui_EffectNode6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box6 = lv_obj_create(ui_EffectNode6);
    lv_obj_set_width(ui_Select_Box6, 50);
    lv_obj_set_height(ui_Select_Box6, 50);
    lv_obj_set_x(ui_Select_Box6, -110);
    lv_obj_set_y(ui_Select_Box6, 42);
    lv_obj_set_align(ui_Select_Box6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box6, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box6, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst2Col);
    ui_object_set_themeable_style_property(ui_Select_Box6, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst2Col);

    ui_PedalIndicater6 = lv_label_create(ui_Select_Box6);
    lv_obj_set_width(ui_PedalIndicater6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater6, -86);
    lv_obj_set_y(ui_PedalIndicater6, 0);
    lv_obj_set_align(ui_PedalIndicater6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater6, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode7 = lv_obj_create(ui_InstSelect2);
    lv_obj_remove_style_all(ui_EffectNode7);
    lv_obj_set_width(ui_EffectNode7, 60);
    lv_obj_set_height(ui_EffectNode7, 50);
    lv_obj_set_x(ui_EffectNode7, -53);
    lv_obj_set_y(ui_EffectNode7, 62);
    lv_obj_set_align(ui_EffectNode7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box7 = lv_obj_create(ui_EffectNode7);
    lv_obj_set_width(ui_Select_Box7, 50);
    lv_obj_set_height(ui_Select_Box7, 50);
    lv_obj_set_x(ui_Select_Box7, -110);
    lv_obj_set_y(ui_Select_Box7, 42);
    lv_obj_set_align(ui_Select_Box7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box7, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box7, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst2Col);
    ui_object_set_themeable_style_property(ui_Select_Box7, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst2Col);

    ui_PedalIndicater7 = lv_label_create(ui_Select_Box7);
    lv_obj_set_width(ui_PedalIndicater7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater7, -86);
    lv_obj_set_y(ui_PedalIndicater7, 0);
    lv_obj_set_align(ui_PedalIndicater7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater7, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode8 = lv_obj_create(ui_InstSelect2);
    lv_obj_remove_style_all(ui_EffectNode8);
    lv_obj_set_width(ui_EffectNode8, 60);
    lv_obj_set_height(ui_EffectNode8, 50);
    lv_obj_set_x(ui_EffectNode8, -53);
    lv_obj_set_y(ui_EffectNode8, 62);
    lv_obj_set_align(ui_EffectNode8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box8 = lv_obj_create(ui_EffectNode8);
    lv_obj_set_width(ui_Select_Box8, 50);
    lv_obj_set_height(ui_Select_Box8, 50);
    lv_obj_set_x(ui_Select_Box8, -110);
    lv_obj_set_y(ui_Select_Box8, 42);
    lv_obj_set_align(ui_Select_Box8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box8, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box8, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst2Col);
    ui_object_set_themeable_style_property(ui_Select_Box8, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst2Col);

    ui_PedalIndicater9 = lv_label_create(ui_Select_Box8);
    lv_obj_set_width(ui_PedalIndicater9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater9, -86);
    lv_obj_set_y(ui_PedalIndicater9, 0);
    lv_obj_set_align(ui_PedalIndicater9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater9, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode9 = lv_obj_create(ui_InstSelect2);
    lv_obj_remove_style_all(ui_EffectNode9);
    lv_obj_set_width(ui_EffectNode9, 60);
    lv_obj_set_height(ui_EffectNode9, 50);
    lv_obj_set_x(ui_EffectNode9, -53);
    lv_obj_set_y(ui_EffectNode9, 62);
    lv_obj_set_align(ui_EffectNode9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box9 = lv_obj_create(ui_EffectNode9);
    lv_obj_set_width(ui_Select_Box9, 50);
    lv_obj_set_height(ui_Select_Box9, 50);
    lv_obj_set_x(ui_Select_Box9, -110);
    lv_obj_set_y(ui_Select_Box9, 42);
    lv_obj_set_align(ui_Select_Box9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box9, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box9, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst2Col);
    ui_object_set_themeable_style_property(ui_Select_Box9, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst2Col);

    ui_PedalIndicater10 = lv_label_create(ui_Select_Box9);
    lv_obj_set_width(ui_PedalIndicater10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater10, -86);
    lv_obj_set_y(ui_PedalIndicater10, 0);
    lv_obj_set_align(ui_PedalIndicater10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater10, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EffectNode10 = lv_obj_create(ui_InstSelect2);
    lv_obj_remove_style_all(ui_EffectNode10);
    lv_obj_set_width(ui_EffectNode10, 60);
    lv_obj_set_height(ui_EffectNode10, 50);
    lv_obj_set_x(ui_EffectNode10, -53);
    lv_obj_set_y(ui_EffectNode10, 62);
    lv_obj_set_align(ui_EffectNode10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EffectNode10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EffectNode10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EffectNode10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select_Box10 = lv_obj_create(ui_EffectNode10);
    lv_obj_set_width(ui_Select_Box10, 50);
    lv_obj_set_height(ui_Select_Box10, 50);
    lv_obj_set_x(ui_Select_Box10, -110);
    lv_obj_set_y(ui_Select_Box10, 42);
    lv_obj_set_align(ui_Select_Box10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Select_Box10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_Box10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Select_Box10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Select_Box10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Select_Box10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_Select_Box10, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select_Box10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Select_Box10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Select_Box10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Select_Box10, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst2Col);
    ui_object_set_themeable_style_property(ui_Select_Box10, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst2Col);

    ui_PedalIndicater11 = lv_label_create(ui_Select_Box10);
    lv_obj_set_width(ui_PedalIndicater11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater11, -86);
    lv_obj_set_y(ui_PedalIndicater11, 0);
    lv_obj_set_align(ui_PedalIndicater11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater11, "+");
    lv_obj_set_style_text_color(ui_PedalIndicater11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EqSelect1 = lv_obj_create(ui_InstSelect2);
    lv_obj_set_width(ui_EqSelect1, 50);
    lv_obj_set_height(ui_EqSelect1, 50);
    lv_obj_set_x(ui_EqSelect1, 150);
    lv_obj_set_y(ui_EqSelect1, 0);
    lv_obj_set_align(ui_EqSelect1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EqSelect1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EqSelect1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_EqSelect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_EqSelect1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_EqSelect1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_EqSelect1, lv_color_hex(0xEAE2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EqSelect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EqSelect1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EqSelect1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_EqSelect1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Inst2Col);
    ui_object_set_themeable_style_property(ui_EqSelect1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Inst2Col);

    ui_PedalIndicater12 = lv_label_create(ui_EqSelect1);
    lv_obj_set_width(ui_PedalIndicater12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PedalIndicater12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalIndicater12, -86);
    lv_obj_set_y(ui_PedalIndicater12, 0);
    lv_obj_set_align(ui_PedalIndicater12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PedalIndicater12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalIndicater12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalIndicater12, "EQ");
    lv_obj_set_style_text_color(ui_PedalIndicater12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalIndicater12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PresetSelect, ui_event_PresetSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box1, ui_event_Select_Box1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box2, ui_event_Select_Box2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box3, ui_event_Select_Box3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box4, ui_event_Select_Box4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box5, ui_event_Select_Box5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EqSelect, ui_event_EqSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box6, ui_event_Select_Box6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box7, ui_event_Select_Box7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box8, ui_event_Select_Box8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box9, ui_event_Select_Box9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Box10, ui_event_Select_Box10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EqSelect1, ui_event_EqSelect1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);
    uic_PresetSelect = ui_PresetSelect;
    uic_VolumeIndicator = ui_VolumeIndicator;

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    uic_PresetSelect = NULL;
    ui_PresetSelect = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    uic_VolumeIndicator = NULL;
    ui_VolumeIndicator = NULL;
    ui_InstSelect1 = NULL;
    ui_EffectNode2 = NULL;
    ui_Select_Box1 = NULL;
    ui_PedalIndicater1 = NULL;
    ui_EffectNode3 = NULL;
    ui_Select_Box2 = NULL;
    ui_PedalIndicater3 = NULL;
    ui_EffectNode1 = NULL;
    ui_Select_Box3 = NULL;
    ui_PedalIndicater2 = NULL;
    ui_EffectNode4 = NULL;
    ui_Select_Box4 = NULL;
    ui_PedalIndicater4 = NULL;
    ui_EffectNode5 = NULL;
    ui_Select_Box5 = NULL;
    ui_PedalIndicater5 = NULL;
    ui_EqSelect = NULL;
    ui_PedalIndicater8 = NULL;
    ui_InstSelect2 = NULL;
    ui_EffectNode6 = NULL;
    ui_Select_Box6 = NULL;
    ui_PedalIndicater6 = NULL;
    ui_EffectNode7 = NULL;
    ui_Select_Box7 = NULL;
    ui_PedalIndicater7 = NULL;
    ui_EffectNode8 = NULL;
    ui_Select_Box8 = NULL;
    ui_PedalIndicater9 = NULL;
    ui_EffectNode9 = NULL;
    ui_Select_Box9 = NULL;
    ui_PedalIndicater10 = NULL;
    ui_EffectNode10 = NULL;
    ui_Select_Box10 = NULL;
    ui_PedalIndicater11 = NULL;
    ui_EqSelect1 = NULL;
    ui_PedalIndicater12 = NULL;

}
