// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern void ui_event_PresetSelect(lv_event_t * e);
extern lv_obj_t * ui_PresetSelect;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_VolumeIndicator;
extern lv_obj_t * ui_InstSelect1;
extern lv_obj_t * ui_EffectNode2;
extern void ui_event_Select_Box1(lv_event_t * e);
extern lv_obj_t * ui_Select_Box1;
extern lv_obj_t * ui_PedalIndicater1;
extern lv_obj_t * ui_EffectNode3;
extern void ui_event_Select_Box2(lv_event_t * e);
extern lv_obj_t * ui_Select_Box2;
extern lv_obj_t * ui_PedalIndicater3;
extern lv_obj_t * ui_EffectNode1;
extern void ui_event_Select_Box3(lv_event_t * e);
extern lv_obj_t * ui_Select_Box3;
extern lv_obj_t * ui_PedalIndicater2;
extern lv_obj_t * ui_EffectNode4;
extern void ui_event_Select_Box4(lv_event_t * e);
extern lv_obj_t * ui_Select_Box4;
extern lv_obj_t * ui_PedalIndicater4;
extern lv_obj_t * ui_EffectNode5;
extern void ui_event_Select_Box5(lv_event_t * e);
extern lv_obj_t * ui_Select_Box5;
extern lv_obj_t * ui_PedalIndicater5;
extern void ui_event_EqSelect(lv_event_t * e);
extern lv_obj_t * ui_EqSelect;
extern lv_obj_t * ui_PedalIndicater8;
extern lv_obj_t * ui_InstSelect2;
extern lv_obj_t * ui_EffectNode6;
extern void ui_event_Select_Box6(lv_event_t * e);
extern lv_obj_t * ui_Select_Box6;
extern lv_obj_t * ui_PedalIndicater6;
extern lv_obj_t * ui_EffectNode7;
extern void ui_event_Select_Box7(lv_event_t * e);
extern lv_obj_t * ui_Select_Box7;
extern lv_obj_t * ui_PedalIndicater7;
extern lv_obj_t * ui_EffectNode8;
extern void ui_event_Select_Box8(lv_event_t * e);
extern lv_obj_t * ui_Select_Box8;
extern lv_obj_t * ui_PedalIndicater9;
extern lv_obj_t * ui_EffectNode9;
extern void ui_event_Select_Box9(lv_event_t * e);
extern lv_obj_t * ui_Select_Box9;
extern lv_obj_t * ui_PedalIndicater10;
extern lv_obj_t * ui_EffectNode10;
extern void ui_event_Select_Box10(lv_event_t * e);
extern lv_obj_t * ui_Select_Box10;
extern lv_obj_t * ui_PedalIndicater11;
extern void ui_event_EqSelect1(lv_event_t * e);
extern lv_obj_t * ui_EqSelect1;
extern lv_obj_t * ui_PedalIndicater12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PresetSelect;
extern lv_obj_t * uic_VolumeIndicator;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

