// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_PEDAL_H
#define UI_PEDAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Pedal
extern void ui_Pedal_screen_init(void);
extern void ui_Pedal_screen_destroy(void);
extern void ui_event_Pedal(lv_event_t * e);
extern lv_obj_t * ui_Pedal;
extern lv_obj_t * ui_PedalDescripton;
extern lv_obj_t * ui_BGEffect;
extern void ui_event_PedalSel1(lv_event_t * e);
extern lv_obj_t * ui_PedalSel1;
extern void ui_event_BackButton1(lv_event_t * e);
extern lv_obj_t * ui_BackButton1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_ParamCont;
extern lv_obj_t * ui_Parameter;
extern lv_obj_t * ui_ParamValue;
extern lv_obj_t * ui_ParamTxt;
extern lv_obj_t * ui_ParamCont1;
extern lv_obj_t * ui_Parameter1;
extern lv_obj_t * ui_ParamValue1;
extern lv_obj_t * ui_ParamTxt1;
extern lv_obj_t * ui_ParamCont2;
extern lv_obj_t * ui_Parameter2;
extern lv_obj_t * ui_ParamValue2;
extern lv_obj_t * ui_ParamTxt2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_ParamCont3;
extern lv_obj_t * ui_Parameter3;
extern lv_obj_t * ui_ParamValue3;
extern lv_obj_t * ui_ParamTxt3;
extern lv_obj_t * ui_ParamCont4;
extern lv_obj_t * ui_Parameter4;
extern lv_obj_t * ui_ParamValue4;
extern lv_obj_t * ui_ParamTxt4;
extern lv_obj_t * ui_ParamCont5;
extern lv_obj_t * ui_Parameter5;
extern lv_obj_t * ui_ParamValue5;
extern lv_obj_t * ui_ParamTxt5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BGEffect;
extern lv_obj_t * uic_ParamTxt;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

