// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_ParamTxt;
lv_obj_t * uic_BGEffect;
lv_obj_t * ui_Pedal = NULL;
lv_obj_t * ui_PedalDescripton = NULL;
lv_obj_t * ui_BGEffect = NULL;
lv_obj_t * ui_PedalSel1 = NULL;
lv_obj_t * ui_BackButton1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_ParamCont = NULL;
lv_obj_t * ui_Parameter = NULL;
lv_obj_t * ui_ParamValue = NULL;
lv_obj_t * ui_ParamTxt = NULL;
lv_obj_t * ui_ParamCont1 = NULL;
lv_obj_t * ui_Parameter1 = NULL;
lv_obj_t * ui_ParamValue1 = NULL;
lv_obj_t * ui_ParamTxt1 = NULL;
lv_obj_t * ui_ParamCont2 = NULL;
lv_obj_t * ui_Parameter2 = NULL;
lv_obj_t * ui_ParamValue2 = NULL;
lv_obj_t * ui_ParamTxt2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_ParamCont3 = NULL;
lv_obj_t * ui_Parameter3 = NULL;
lv_obj_t * ui_ParamValue3 = NULL;
lv_obj_t * ui_ParamTxt3 = NULL;
lv_obj_t * ui_ParamCont4 = NULL;
lv_obj_t * ui_Parameter4 = NULL;
lv_obj_t * ui_ParamValue4 = NULL;
lv_obj_t * ui_ParamTxt4 = NULL;
lv_obj_t * ui_ParamCont5 = NULL;
lv_obj_t * ui_Parameter5 = NULL;
lv_obj_t * ui_ParamValue5 = NULL;
lv_obj_t * ui_ParamTxt5 = NULL;
// event funtions
void ui_event_Pedal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        createGroupPedal(e);
    }
}

void ui_event_PedalSel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_UpdatePedalFromDropdown(e);
        uiUpdatePedalScreen(e);
    }
}

void ui_event_BackButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        createGroupMain(e);
        ui_event_save_pedal(e);
    }
}

// build funtions

void ui_Pedal_screen_init(void)
{
    ui_Pedal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Pedal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pedal, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pedal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PedalDescripton = lv_label_create(ui_Pedal);
    lv_obj_set_width(ui_PedalDescripton, lv_pct(31));
    lv_obj_set_height(ui_PedalDescripton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalDescripton, 0);
    lv_obj_set_y(ui_PedalDescripton, 65);
    lv_obj_set_align(ui_PedalDescripton, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_PedalDescripton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PedalDescripton, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PedalDescripton, "Short description of the pedal, what it does, what each parameter does etc.");
    lv_obj_set_style_text_color(ui_PedalDescripton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalDescripton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PedalDescripton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGEffect = lv_label_create(ui_Pedal);
    lv_obj_set_width(ui_BGEffect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BGEffect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BGEffect, 0);
    lv_obj_set_y(ui_BGEffect, 109);
    lv_obj_set_align(ui_BGEffect, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BGEffect, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BGEffect, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BGEffect, "01:");
    ui_object_set_themeable_style_property(ui_BGEffect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_BGEffect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_text_letter_space(ui_BGEffect, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_BGEffect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BGEffect, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BGEffect, &ui_font_IndexFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_BGEffect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_BGEffect, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PedalSel1 = lv_dropdown_create(ui_Pedal);
    lv_dropdown_set_options(ui_PedalSel1,
                            "01: Bypass\n02: Distortion\n03: Chorus\n04: Noise Gate\n05: Flanger\n06: Compressor\n07: Tremolo");
    lv_obj_set_width(ui_PedalSel1, 150);
    lv_obj_set_height(ui_PedalSel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PedalSel1, 0);
    lv_obj_set_y(ui_PedalSel1, 15);
    lv_obj_set_align(ui_PedalSel1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PedalSel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_PedalSel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_PedalSel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_radius(ui_PedalSel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PedalSel1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PedalSel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PedalSel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_PedalSel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_border_color(ui_PedalSel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PedalSel1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PedalSel1, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_PedalSel1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_radius(lv_dropdown_get_list(ui_PedalSel1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_PedalSel1), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_PedalSel1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_PedalSel1), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_PedalSel1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton1 = lv_button_create(ui_Pedal);
    lv_obj_set_width(ui_BackButton1, 100);
    lv_obj_set_height(ui_BackButton1, 50);
    lv_obj_set_flex_flow(ui_BackButton1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BackButton1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BackButton1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackButton1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackButton1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BackButton1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_BackButton1, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_BackButton1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label3 = lv_label_create(ui_Pedal);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -191);
    lv_obj_set_y(ui_Label3, -136);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Back");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_Container1 = lv_obj_create(ui_Pedal);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 260);
    lv_obj_set_x(ui_Container1, -190);
    lv_obj_set_y(ui_Container1, 30);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ParamCont = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_ParamCont);
    lv_obj_set_width(ui_ParamCont, 100);
    lv_obj_set_height(ui_ParamCont, 57);
    lv_obj_set_x(ui_ParamCont, -163);
    lv_obj_set_y(ui_ParamCont, 3);
    lv_obj_set_align(ui_ParamCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ParamCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ParamCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ParamCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Parameter = lv_arc_create(ui_ParamCont);
    lv_obj_set_width(ui_Parameter, 25);
    lv_obj_set_height(ui_Parameter, 25);
    lv_obj_set_x(ui_Parameter, 185);
    lv_obj_set_y(ui_Parameter, 35);
    lv_obj_set_align(ui_Parameter, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Parameter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Parameter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_Parameter, 75);
    lv_obj_set_style_radius(ui_Parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Parameter, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Parameter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Parameter, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Parameter, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Parameter, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Parameter, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Parameter, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_Parameter, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Parameter, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parameter, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Parameter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ParamValue = lv_label_create(ui_ParamCont);
    lv_obj_set_width(ui_ParamValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamValue, 185);
    lv_obj_set_y(ui_ParamValue, 70);
    lv_obj_set_align(ui_ParamValue, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamValue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamValue, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamValue, "0");
    ui_object_set_themeable_style_property(ui_ParamValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamTxt = lv_label_create(ui_ParamCont);
    lv_obj_set_width(ui_ParamTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamTxt, 185);
    lv_obj_set_y(ui_ParamTxt, 70);
    lv_obj_set_align(ui_ParamTxt, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamTxt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamTxt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamTxt, "ParamTxt");
    ui_object_set_themeable_style_property(ui_ParamTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamCont1 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_ParamCont1);
    lv_obj_set_width(ui_ParamCont1, 100);
    lv_obj_set_height(ui_ParamCont1, 57);
    lv_obj_set_x(ui_ParamCont1, -163);
    lv_obj_set_y(ui_ParamCont1, 3);
    lv_obj_set_align(ui_ParamCont1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ParamCont1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ParamCont1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ParamCont1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Parameter1 = lv_arc_create(ui_ParamCont1);
    lv_obj_set_width(ui_Parameter1, 25);
    lv_obj_set_height(ui_Parameter1, 25);
    lv_obj_set_x(ui_Parameter1, 185);
    lv_obj_set_y(ui_Parameter1, 35);
    lv_obj_set_align(ui_Parameter1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Parameter1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Parameter1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_Parameter1, 75);
    lv_obj_set_style_radius(ui_Parameter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Parameter1, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Parameter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Parameter1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Parameter1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Parameter1, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Parameter1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Parameter1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_Parameter1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Parameter1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parameter1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Parameter1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ParamValue1 = lv_label_create(ui_ParamCont1);
    lv_obj_set_width(ui_ParamValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamValue1, 185);
    lv_obj_set_y(ui_ParamValue1, 70);
    lv_obj_set_align(ui_ParamValue1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamValue1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamValue1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamValue1, "0");
    ui_object_set_themeable_style_property(ui_ParamValue1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamValue1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamTxt1 = lv_label_create(ui_ParamCont1);
    lv_obj_set_width(ui_ParamTxt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamTxt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamTxt1, 185);
    lv_obj_set_y(ui_ParamTxt1, 70);
    lv_obj_set_align(ui_ParamTxt1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamTxt1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamTxt1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamTxt1, "ParamTxt");
    ui_object_set_themeable_style_property(ui_ParamTxt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamTxt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamCont2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_ParamCont2);
    lv_obj_set_width(ui_ParamCont2, 100);
    lv_obj_set_height(ui_ParamCont2, 57);
    lv_obj_set_x(ui_ParamCont2, -163);
    lv_obj_set_y(ui_ParamCont2, 3);
    lv_obj_set_align(ui_ParamCont2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ParamCont2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ParamCont2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ParamCont2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Parameter2 = lv_arc_create(ui_ParamCont2);
    lv_obj_set_width(ui_Parameter2, 25);
    lv_obj_set_height(ui_Parameter2, 25);
    lv_obj_set_x(ui_Parameter2, 185);
    lv_obj_set_y(ui_Parameter2, 35);
    lv_obj_set_align(ui_Parameter2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Parameter2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Parameter2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_Parameter2, 75);
    lv_obj_set_style_radius(ui_Parameter2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Parameter2, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Parameter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Parameter2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Parameter2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Parameter2, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Parameter2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Parameter2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_Parameter2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Parameter2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parameter2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Parameter2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ParamValue2 = lv_label_create(ui_ParamCont2);
    lv_obj_set_width(ui_ParamValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamValue2, 185);
    lv_obj_set_y(ui_ParamValue2, 70);
    lv_obj_set_align(ui_ParamValue2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamValue2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamValue2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamValue2, "0");
    ui_object_set_themeable_style_property(ui_ParamValue2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamValue2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamTxt2 = lv_label_create(ui_ParamCont2);
    lv_obj_set_width(ui_ParamTxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamTxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamTxt2, 185);
    lv_obj_set_y(ui_ParamTxt2, 70);
    lv_obj_set_align(ui_ParamTxt2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamTxt2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamTxt2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamTxt2, "ParamTxt");
    ui_object_set_themeable_style_property(ui_ParamTxt2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamTxt2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_Container3 = lv_obj_create(ui_Pedal);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, 260);
    lv_obj_set_x(ui_Container3, 190);
    lv_obj_set_y(ui_Container3, 30);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ParamCont3 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ParamCont3);
    lv_obj_set_width(ui_ParamCont3, 100);
    lv_obj_set_height(ui_ParamCont3, 57);
    lv_obj_set_x(ui_ParamCont3, -163);
    lv_obj_set_y(ui_ParamCont3, 3);
    lv_obj_set_align(ui_ParamCont3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ParamCont3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ParamCont3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ParamCont3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Parameter3 = lv_arc_create(ui_ParamCont3);
    lv_obj_set_width(ui_Parameter3, 25);
    lv_obj_set_height(ui_Parameter3, 25);
    lv_obj_set_x(ui_Parameter3, 185);
    lv_obj_set_y(ui_Parameter3, 35);
    lv_obj_set_align(ui_Parameter3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Parameter3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Parameter3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_Parameter3, 75);
    lv_obj_set_style_radius(ui_Parameter3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Parameter3, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Parameter3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Parameter3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Parameter3, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Parameter3, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Parameter3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Parameter3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_Parameter3, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Parameter3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parameter3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Parameter3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ParamValue3 = lv_label_create(ui_ParamCont3);
    lv_obj_set_width(ui_ParamValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamValue3, 185);
    lv_obj_set_y(ui_ParamValue3, 70);
    lv_obj_set_align(ui_ParamValue3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamValue3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamValue3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamValue3, "0");
    ui_object_set_themeable_style_property(ui_ParamValue3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamValue3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamTxt3 = lv_label_create(ui_ParamCont3);
    lv_obj_set_width(ui_ParamTxt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamTxt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamTxt3, 185);
    lv_obj_set_y(ui_ParamTxt3, 70);
    lv_obj_set_align(ui_ParamTxt3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamTxt3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamTxt3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamTxt3, "ParamTxt");
    ui_object_set_themeable_style_property(ui_ParamTxt3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamTxt3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamCont4 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ParamCont4);
    lv_obj_set_width(ui_ParamCont4, 100);
    lv_obj_set_height(ui_ParamCont4, 57);
    lv_obj_set_x(ui_ParamCont4, -163);
    lv_obj_set_y(ui_ParamCont4, 3);
    lv_obj_set_align(ui_ParamCont4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ParamCont4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ParamCont4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ParamCont4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Parameter4 = lv_arc_create(ui_ParamCont4);
    lv_obj_set_width(ui_Parameter4, 25);
    lv_obj_set_height(ui_Parameter4, 25);
    lv_obj_set_x(ui_Parameter4, 185);
    lv_obj_set_y(ui_Parameter4, 35);
    lv_obj_set_align(ui_Parameter4, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Parameter4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Parameter4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_Parameter4, 75);
    lv_obj_set_style_radius(ui_Parameter4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Parameter4, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Parameter4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Parameter4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Parameter4, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Parameter4, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Parameter4, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Parameter4, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_Parameter4, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Parameter4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parameter4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Parameter4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ParamValue4 = lv_label_create(ui_ParamCont4);
    lv_obj_set_width(ui_ParamValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamValue4, 185);
    lv_obj_set_y(ui_ParamValue4, 70);
    lv_obj_set_align(ui_ParamValue4, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamValue4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamValue4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamValue4, "0");
    ui_object_set_themeable_style_property(ui_ParamValue4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamValue4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamTxt4 = lv_label_create(ui_ParamCont4);
    lv_obj_set_width(ui_ParamTxt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamTxt4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamTxt4, 185);
    lv_obj_set_y(ui_ParamTxt4, 70);
    lv_obj_set_align(ui_ParamTxt4, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamTxt4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamTxt4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamTxt4, "ParamTxt");
    ui_object_set_themeable_style_property(ui_ParamTxt4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamTxt4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamCont5 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ParamCont5);
    lv_obj_set_width(ui_ParamCont5, 100);
    lv_obj_set_height(ui_ParamCont5, 57);
    lv_obj_set_x(ui_ParamCont5, -163);
    lv_obj_set_y(ui_ParamCont5, 3);
    lv_obj_set_align(ui_ParamCont5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ParamCont5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ParamCont5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ParamCont5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Parameter5 = lv_arc_create(ui_ParamCont5);
    lv_obj_set_width(ui_Parameter5, 25);
    lv_obj_set_height(ui_Parameter5, 25);
    lv_obj_set_x(ui_Parameter5, 185);
    lv_obj_set_y(ui_Parameter5, 35);
    lv_obj_set_align(ui_Parameter5, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Parameter5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Parameter5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_Parameter5, 75);
    lv_obj_set_style_radius(ui_Parameter5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Parameter5, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Parameter5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Parameter5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Parameter5, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Parameter5, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Parameter5, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Parameter5, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_neutral);
    lv_obj_set_style_arc_width(ui_Parameter5, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Parameter5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parameter5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Parameter5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ParamValue5 = lv_label_create(ui_ParamCont5);
    lv_obj_set_width(ui_ParamValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamValue5, 185);
    lv_obj_set_y(ui_ParamValue5, 70);
    lv_obj_set_align(ui_ParamValue5, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamValue5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamValue5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamValue5, "0");
    ui_object_set_themeable_style_property(ui_ParamValue5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamValue5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_ParamTxt5 = lv_label_create(ui_ParamCont5);
    lv_obj_set_width(ui_ParamTxt5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamTxt5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamTxt5, 185);
    lv_obj_set_y(ui_ParamTxt5, 70);
    lv_obj_set_align(ui_ParamTxt5, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ParamTxt5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParamTxt5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ParamTxt5, "ParamTxt");
    ui_object_set_themeable_style_property(ui_ParamTxt5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_ParamTxt5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    lv_obj_add_event_cb(ui_PedalSel1, ui_event_PedalSel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton1, ui_event_BackButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pedal, ui_event_Pedal, LV_EVENT_ALL, NULL);
    uic_BGEffect = ui_BGEffect;
    uic_ParamTxt = ui_ParamTxt;

}

void ui_Pedal_screen_destroy(void)
{
    if(ui_Pedal) lv_obj_del(ui_Pedal);

    // NULL screen variables
    ui_Pedal = NULL;
    ui_PedalDescripton = NULL;
    uic_BGEffect = NULL;
    ui_BGEffect = NULL;
    ui_PedalSel1 = NULL;
    ui_BackButton1 = NULL;
    ui_Label3 = NULL;
    ui_Container1 = NULL;
    ui_ParamCont = NULL;
    ui_Parameter = NULL;
    ui_ParamValue = NULL;
    uic_ParamTxt = NULL;
    ui_ParamTxt = NULL;
    ui_ParamCont1 = NULL;
    ui_Parameter1 = NULL;
    ui_ParamValue1 = NULL;
    ui_ParamTxt1 = NULL;
    ui_ParamCont2 = NULL;
    ui_Parameter2 = NULL;
    ui_ParamValue2 = NULL;
    ui_ParamTxt2 = NULL;
    ui_Container3 = NULL;
    ui_ParamCont3 = NULL;
    ui_Parameter3 = NULL;
    ui_ParamValue3 = NULL;
    ui_ParamTxt3 = NULL;
    ui_ParamCont4 = NULL;
    ui_Parameter4 = NULL;
    ui_ParamValue4 = NULL;
    ui_ParamTxt4 = NULL;
    ui_ParamCont5 = NULL;
    ui_Parameter5 = NULL;
    ui_ParamValue5 = NULL;
    ui_ParamTxt5 = NULL;

}
