// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_TUNER_H
#define UI_TUNER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tuner
extern void ui_Tuner_screen_init(void);
extern void ui_Tuner_screen_destroy(void);
extern void ui_event_Tuner(lv_event_t * e);
extern lv_obj_t * ui_Tuner;
extern void ui_event_BackButton2(lv_event_t * e);
extern lv_obj_t * ui_BackButton2;
extern lv_obj_t * ui_Back;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_TunerImage;
extern lv_obj_t * ui_TunerValueLabel;
extern lv_obj_t * ui_Flat;
extern lv_obj_t * ui_Sharp;
extern lv_obj_t * ui_TunerIndicator;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

