// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Tuner = NULL;
lv_obj_t * ui_BackButton2 = NULL;
lv_obj_t * ui_Back = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_TunerImage = NULL;
lv_obj_t * ui_TunerValueLabel = NULL;
lv_obj_t * ui_Flat = NULL;
lv_obj_t * ui_Sharp = NULL;
lv_obj_t * ui_TunerIndicator = NULL;
// event funtions
void ui_event_Tuner(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        createGroupTuner(e);
    }
}

void ui_event_BackButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ui_group_set_screen_main(e);
        ui_event_save_pedal(e);
    }
}

// build funtions

void ui_Tuner_screen_init(void)
{
    ui_Tuner = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Tuner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tuner, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tuner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton2 = lv_button_create(ui_Tuner);
    lv_obj_set_width(ui_BackButton2, 100);
    lv_obj_set_height(ui_BackButton2, 50);
    lv_obj_set_flex_flow(ui_BackButton2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BackButton2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BackButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton2, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackButton2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BackButton2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackButton2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackButton2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BackButton2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_BackButton2, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_BackButton2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Back = lv_label_create(ui_Tuner);
    lv_obj_set_width(ui_Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back, -191);
    lv_obj_set_y(ui_Back, -136);
    lv_obj_set_align(ui_Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back, "Back");
    ui_object_set_themeable_style_property(ui_Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_Container2 = lv_obj_create(ui_Tuner);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 480);
    lv_obj_set_height(ui_Container2, 100);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TunerImage = lv_image_create(ui_Tuner);
    lv_image_set_src(ui_TunerImage, &ui_img_tunerasset_png);
    lv_obj_set_width(ui_TunerImage, LV_SIZE_CONTENT);   /// 330
    lv_obj_set_height(ui_TunerImage, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_TunerImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TunerImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TunerImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TunerValueLabel = lv_label_create(ui_Tuner);
    lv_obj_set_width(ui_TunerValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TunerValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TunerValueLabel, 0);
    lv_obj_set_y(ui_TunerValueLabel, -80);
    lv_obj_set_align(ui_TunerValueLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_TunerValueLabel, "Param2Txt");
    ui_object_set_themeable_style_property(ui_TunerValueLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_neutral);
    ui_object_set_themeable_style_property(ui_TunerValueLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_neutral);

    ui_Flat = lv_image_create(ui_Tuner);
    lv_image_set_src(ui_Flat, &ui_img_flatindicator_png);
    lv_obj_set_width(ui_Flat, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Flat, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Flat, -191);
    lv_obj_set_y(ui_Flat, 0);
    lv_obj_set_align(ui_Flat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Flat, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Flat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sharp = lv_image_create(ui_Tuner);
    lv_image_set_src(ui_Sharp, &ui_img_flatindicator_png);
    lv_obj_set_width(ui_Sharp, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Sharp, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Sharp, 189);
    lv_obj_set_y(ui_Sharp, -1);
    lv_obj_set_align(ui_Sharp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sharp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Sharp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Sharp, 9000);

    ui_TunerIndicator = lv_slider_create(ui_Tuner);
    lv_slider_set_value(ui_TunerIndicator, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_TunerIndicator) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_TunerIndicator, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_TunerIndicator, 240);
    lv_obj_set_height(ui_TunerIndicator, 10);
    lv_obj_set_align(ui_TunerIndicator, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TunerIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TunerIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TunerIndicator, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TunerIndicator, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TunerIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TunerIndicator, lv_color_hex(0x00F5D4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TunerIndicator, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TunerIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TunerIndicator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TunerIndicator, 40, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TunerIndicator, 40, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TunerIndicator, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TunerIndicator,
                                                                                                     lv_obj_get_style_pad_right(ui_TunerIndicator, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_BackButton2, ui_event_BackButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tuner, ui_event_Tuner, LV_EVENT_ALL, NULL);

}

void ui_Tuner_screen_destroy(void)
{
    if(ui_Tuner) lv_obj_del(ui_Tuner);

    // NULL screen variables
    ui_Tuner = NULL;
    ui_BackButton2 = NULL;
    ui_Back = NULL;
    ui_Container2 = NULL;
    ui_TunerImage = NULL;
    ui_TunerValueLabel = NULL;
    ui_Flat = NULL;
    ui_Sharp = NULL;
    ui_TunerIndicator = NULL;

}
